version: '3'

services:
    db:
        image: mariadb:10.8
        container_name: db
        ports:
            - "3306:3306"
        environment:
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_USER}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    php:
        build:
            context: ./docker/php7
        container_name: php7
        depends_on:
            - db
        volumes:
            - ${PWD}:/var/www/todo_list
        ports:
            - "8080:80"
        working_dir: /var/www/todo_list

