FROM php:7.3-apache-stretch
MAINTAINER Adnane Nouri <adnane.nouri@inetum.com>

ENV DEBIAN_FRONTEND noninteractive

# Update and Install tools.
RUN apt-get update && \
    apt-get -y install \
    apt-utils \
    locales \
    software-properties-common \
    curl \
    wget \
    zip \
    vim \
    libxml2-utils \
    apache2 \
    zip \
    unzip \
    libicu-dev \
    git

# Install and enable the intl extension (used for validators).
RUN docker-php-ext-configure intl && \
    docker-php-ext-install intl

# install and activate Opcache. (only in prod env, live debug with apiPlaform for dev environement)
#RUN docker-php-ext-install opcache
#ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS="0"
#ADD opcache.ini "$PHP_INI_DIR/conf.d/opcache.ini"

# Install composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install symfony cli.
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony

# Install and activate mysqli and mysql pdo extensions.
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN docker-php-ext-enable mysqli pdo pdo_mysql

# Add apache variables.
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2

# Update the default apache site with the config we created.
ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf

# Activate header, env and rewrite apache module
RUN a2enmod env && \
    a2enmod headers && \
    a2enmod rewrite


# Install and activate xdebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> "$PHP_INI_DIR/conf.d/xdebug.ini" \
    && echo "xdebug.remote_autostart=off" >> "$PHP_INI_DIR/conf.d/xdebug.ini"


RUN mkdir -p $APACHE_RUN_DIR $APACHE_LOCK_DIR $APACHE_LOG_DIR

VOLUME ["/var/www/todo_list"]

EXPOSE 80

ENTRYPOINT [ "/usr/sbin/apache2" ]
CMD ["-D", "FOREGROUND"]
